Repository Kernel360/KBE5_CKT_BE, pull requests merged in 2025-06, with the labels that each got.

#15 feat: 로그인된 업체 정보 조회 기능 개발
  admin/build.gradle
  admin/src/main/java/kernel360/ckt/admin/application/CompanyService.java
  admin/src/main/java/kernel360/ckt/admin/config/SecurityConfig.java
  admin/src/main/java/kernel360/ckt/admin/ui/CompanyController.java
  admin/src/main/java/kernel360/ckt/admin/ui/dto/response/CompanyMeResponse.java
  auth/src/main/java/kernel360/ckt/auth/config/JwtTokenProvider.java
  auth/src/main/java/kernel360/ckt/auth/domain/RefreshTokenStatus.java
  gateway/src/main/java/kernel360/ckt/gateway/GatewayApplication.java
  gateway/src/main/java/kernel360/ckt/gateway/config/GatewayConfig.java
Labels: ✨ feat

#25 fix: db 테이블 생성 시 quoted 로 인해 json 속성에서 충돌나는 버그 수정
  admin/src/main/resources/application.yml
  auth/src/main/resources/application.yml
Labels: 🐛 bug

#28 refactor: 스네이크 케이스 네이밍 적용
  admin/src/main/resources/application.yml
  auth/src/main/resources/application.yml
  collector/src/main/resources/application.yml
Labels: ♻️ refactor

#45 fix: 운행 일지 개발 머지 충돌 해결
  admin/src/main/java/kernel360/ckt/admin/application/ExcelExportService.java
  admin/src/main/java/kernel360/ckt/admin/application/LogSummaryService.java
  admin/src/main/java/kernel360/ckt/admin/infra/repository/RouteLogRepository.java
  admin/src/main/java/kernel360/ckt/admin/infra/repository/jpa/RouteJpaRepository.java
  admin/src/main/java/kernel360/ckt/admin/ui/DrivingLogController.java
  core/src/main/java/kernel360/ckt/core/repository/RouteRepository.java
Labels: 🐛 bug

#43 chore: 환경 설정 분리 및 변경
  admin/src/main/resources/application-local.yml
  admin/src/main/resources/application-prod.yml
  admin/src/main/resources/application.yml
  auth/src/main/resources/application-local.yml
  auth/src/main/resources/application-prod.yml
  auth/src/main/resources/application.yml
  collector/src/main/resources/application-local.yml
  collector/src/main/resources/application-prod.yml
  collector/src/main/resources/application.yml
  docker-compose.yml
  gateway/src/main/java/kernel360/ckt/gateway/config/GatewayConfig.java
  gateway/src/main/resources/application-docker.yml
  gateway/src/main/resources/application-local.yml
  gateway/src/main/resources/application-prod.yml
  gateway/src/main/resources/application.yml
Labels: 🧹 chore

#81 feat: admin/auth 모듈에 글로벌 예외 처리기 및 요청 바디 캐싱 필터 추가
  admin/src/main/java/kernel360/ckt/admin/common/exception/GlobalExceptionHandler.java
  auth/src/main/java/kernel360/ckt/auth/common/exception/GlobalExceptionHandler.java
Labels: ✨ feat
