Repository Kernel360/KBE5_CKT_BE, pull requests merged in 2025-07, with the labels that each got.

#96 feat: 고객 도메인에 company_id 및 delete_yn 필드 추가 및 로직 반영
  admin/src/main/java/kernel360/ckt/admin/application/port/CustomerRepository.java
  admin/src/main/java/kernel360/ckt/admin/application/service/CustomerService.java
  admin/src/main/java/kernel360/ckt/admin/infra/CustomerRepositoryAdapter.java
  admin/src/main/java/kernel360/ckt/admin/infra/jpa/CustomerJpaRepository.java
  core/src/main/java/kernel360/ckt/core/domain/entity/CustomerEntity.java
Labels: ✨ feat

#105 fix: CustomerEntity의 company_id 필드 nullable 설정 수정
  core/src/main/java/kernel360/ckt/core/domain/entity/CustomerEntity.java
Labels: 🩹 fix

#109 refactor: 프론트 변경 사항에 맞춰 운행일지 관련 api 리팩토링
  admin/src/main/java/kernel360/ckt/admin/application/service/DrivingLogService.java
  admin/src/main/java/kernel360/ckt/admin/application/service/command/DrivingLogListCommand.java
  admin/src/main/java/kernel360/ckt/admin/application/service/dto/DrivingLogListDto.java
  admin/src/main/java/kernel360/ckt/admin/infra/jdbc/DrivingLogJdbcTemplate.java
  admin/src/main/java/kernel360/ckt/admin/infra/jpa/DrivingLogJpaRepository.java
  admin/src/main/java/kernel360/ckt/admin/ui/DrivingLogController.java
  admin/src/main/java/kernel360/ckt/admin/ui/dto/request/DrivingLogListRequest.java
  admin/src/main/java/kernel360/ckt/admin/ui/dto/request/DrivingLogUpdateRequest.java
  admin/src/main/java/kernel360/ckt/admin/ui/dto/response/DrivingLogResponse.java
  admin/src/main/java/kernel360/ckt/admin/ui/dto/response/DrivingLogUpdateResponse.java
  core/src/main/java/kernel360/ckt/core/domain/entity/DrivingLogEntity.java
  core/src/main/java/kernel360/ckt/core/domain/enums/DrivingType.java
Labels: ♻️ refactor

#117 feat: 시동은 켜졌지만 렌탈 정보가 없는 차량 도난 분류 기능 추가(실시간 관제)
  admin/src/main/java/kernel360/ckt/admin/application/port/VehicleRepository.java
  admin/src/main/java/kernel360/ckt/admin/application/service/VehicleControlTowerService.java
  admin/src/main/java/kernel360/ckt/admin/infra/VehicleRepositoryAdapter.java
  admin/src/main/java/kernel360/ckt/admin/infra/jpa/VehicleJpaRepository.java
  admin/src/main/java/kernel360/ckt/admin/ui/dto/response/ControlTowerSummaryResponse.java
  admin/src/main/java/kernel360/ckt/admin/ui/dto/response/RunningVehicleResponse.java
Labels: ✨ feat

#79 feat: RabbitMQ + SSE 기능 구현
  collector/build.gradle
  collector/src/main/java/kernel360/ckt/collector/config/AsyncConfig.java
  collector/src/main/java/kernel360/ckt/collector/config/RabbitConfig.java
  collector/src/main/java/kernel360/ckt/collector/config/RabbitListenerConfig.java
  collector/src/main/java/kernel360/ckt/collector/config/SseEmitterManager.java
  collector/src/main/java/kernel360/ckt/collector/consumer/GpsDataConsumer.java
  collector/src/main/java/kernel360/ckt/collector/consumer/GpsViewConsumer.java
  collector/src/main/java/kernel360/ckt/collector/ui/SseController.java
  collector/src/main/java/kernel360/ckt/collector/ui/VehicleCollectorController.java
  collector/src/main/resources/application-consumer.yml
  collector/src/main/resources/application.yml
  docker-compose.yml
  gateway/src/main/java/kernel360/ckt/gateway/filter/JwtAuthenticationFilter.java
  gateway/src/main/resources/application-docker.yml
  gateway/src/main/resources/application.yml
  prometheus/prometheus.yml
Labels: ✨ feat

#130 fix: 운행 차량 수 계산 시 도난 차량 제외
  admin/src/main/java/kernel360/ckt/admin/application/service/VehicleControlTowerService.java
Labels: 🩹 fix
